Add hw9
Sakamoto505/test-guru pull request #11
Opened 2022-07-25 23:13 UTC by Sakamoto505

1. Добавьте в сессию идентификатор пользователя после его регистрации
2. Создайте хэлпер для flash сообщений
3. Реализуйте выход пользователя из системы
4. Создайте навигацию с названием проекта и ссылками для регистрации/логина/выхода пользователя. Если пользователь находится в системе - выводить сообщение Welcome, <user name> Guru. Название проекта должно быть ссылкой и вести на главную страницу приложения.
5. Разрешите действия над остальными ресурсами только для пользователя который вошел в систему
6. С помощью механизма куки реализуйте перенаправление пользователя после логина на ту страницу куда он хотел попасть изначально
7. Проверяйте формат и уникальность атрибута email для пользователя
8. Используйте объект текущего пользователя при старте прохождения теста

2022-07-26 06:40 UTC, VidgarVii requested changes

2022-07-26 06:40 UTC, VidgarVii commented on app/assets/stylesheets/nav.scss
> +}
No new lina at end of file

2022-07-26 06:40 UTC, VidgarVii commented on app/controllers/application_controller.rb
> +  before_action :authenticate_user!
не всем страница требуется проверка аутентификации. Лучше этот колбек вызывать там где он нужен.
А вот когда будем делать админку, можно будет вызывать этот колбек из родительского класса

2022-07-26 06:40 UTC, VidgarVii commented on app/controllers/sessions_controller.rb
> +      redirect_to cookies[:return_to_url] || tests_path
Вот здесь можно сразу удалить данные из кук. delete возвращает значение, которое удалил

2022-07-26 06:40 UTC, VidgarVii commented on app/helpers/application_helper.rb
> +    flash.map do |key, msg|
объект flash доступен без входящего аргумента
Предлагаю тут передавать тип сообщения. И чтобы метод возвращал только сообщение определённого типа. Там можно сделать верстку более гибкой. И разные типы сообщений можно будет показывать в разных частях экрана

2022-07-26 06:40 UTC, VidgarVii commented on app/helpers/application_helper.rb
> +      content_tag :div, msg, id: key, class: 'flash alert'
стиль можно задавать по типу сообщения. А не только  alert

2022-07-26 06:40 UTC, VidgarVii commented on app/helpers/application_helper.rb
> +      content_tag :div, msg, id: key, class: 'flash alert'
content_tag можно заменить более современным tag методом

2022-07-26 06:40 UTC, VidgarVii commented on app/views/sessions/_form.html.erb
> +<%end %>
No new lina at end of file
таких вещей вообще не должно быть в коде

2022-07-26 19:03 UTC, VidgarVii requested changes

2022-07-26 19:03 UTC, VidgarVii commented on app/views/users/_form.html.erb
> +<% end %>
надо взять в привычку следить за No new lina at end of file

2022-07-26 21:07 UTC, Sakamoto505 commented on app/views/users/_form.html.erb
> +<% end %>
Всегда забываю, что рубокоп не исправляет эти файлы.
Щас сделаю настройку. 
Это все ?

2022-07-27 07:01 UTC, VidgarVii requested changes

2022-07-27 07:01 UTC, VidgarVii commented on app/controllers/application_controller.rb
> +  before_action :authenticate_user!
не исправлено

2022-07-27 07:01 UTC, VidgarVii commented on app/views/sessions/new.html.erb
> +<%= link_to 'Back', root_path %>
не исправлено

2022-07-27 22:29 UTC, merged